name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Extract database name from SQL script
        id: extract-db
        run: |
          # Look for the first line with "USE DATABASE" and extract the database name
          DB_NAME=$(grep -i 'USE DATABASE' $GITHUB_WORKSPACE/migrations/*.sql | head -n 1 | awk '{print $3}' | tr -d ';' | tr -d ' ')

          echo "Database found: $DB_NAME"
          if [ -z "$DB_NAME" ]; then
            echo "No database name found. Exiting."
            exit 1
          fi
          echo "::set-output name=database::$DB_NAME"

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_DATABASE: ${{ steps.extract-db.outputs.database }}  # Use the extracted database name
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          echo "Using database: $SF_DATABASE"  # Debug line
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
